server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wms_db
    username: wmsadmin
    password: wmsadminpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        tenant_identifier_resolver: com.superware.wms.inventory.config.TenantIdentifierResolver
  autoconfigure:
    exclude:
      - com.superware.wms.security.config.WmsSecurityAutoConfig

logging:
  level:
    com.superware.wms: DEBUG